apiVersion: apps/v1
kind: Deployment

metadata:
  name: myweb-deploy

spec:
  replicas: 2

  selector:
    matchLabels:
      app: myweb

  template:
    metadata:
      labels:
        app: myweb

    spec:
      containers:
      - name: myweb

        image: sihyuk11/myweb:v1

        ports:
        - containerPort: 80
